export const STAGES: Record<number, string> = {
  1: "C, G and F major · root positions",
  2: "First rhythms · C–F–G with diagrams",
  3: "More major root positions",
  4: "B and Bb major · root positions",
  5: "All remaining major root positions",
  6: "Familiar minor root positions",
  7: "Major and minor rhythms · with diagrams",
  8: "All remaining minor root positions",
  9: "First inversions · familiar triads",
  10: "First inversions · remaining triads",
  11: "Second inversions · familiar triads",
  12: "Second inversions · remaining triads",
  13: "Smooth triad progressions · rhythms in every key",
  14: "Seventh chords · root shapes",
  15: "Seventh chords · first inversions",
  16: "Seventh chords · second inversions",
  17: "Blues and jazz rhythms",
  18: "Sixth, diminished and augmented · root shapes",
  19: "Sixth, diminished and augmented · first inversions",
  20: "Sixth, diminished and augmented · second inversions",
  21: "Walkdowns, walk-ups and ballads",
};

